module.exports.login = require('./login')
module.exports.home = require('./home')
module.exports.recs = require('./recs')
module.exports.movie = require('./movie')
module.exports.logout = require('./logout')
